name: "Build with provenance"
on:
  workflow_dispatch:
    inputs:
      flakeref:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Install nix
      uses: cachix/install-nix-action@v22
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build with provenance
      run: ./nix-build-with-provenance.sh ${{ github.event.inputs.flakeref }}
      env:
        PROVENANCE_INVOCATION_ID: ${{ github.run_number }}
        PROVENANCE_BUILDER_ID: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        PROVENANCE_BUILD_TYPE: TBD

    - name: Preview provenance
      run: cat provenance.json | jq .

    - name: Upload provenance artifact
      uses: actions/upload-artifact@v4
      with:
        name: provenance
        path: provenance.json
